### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by KevinRoebert** [macos-fuse-t/fuse-t#1]
Will the source code for this project also be published? How do I know that the program does what it is supposed to do?

**Comment by nhooyr** [comment]
It's quite misleading to have a github repo for it but with nothing in there except for the license and some docs. At a cursory glance it makes it seem like it's open source but it's not...

**Comment by macos-fuse-t** [comment]
I'm going to put the source code of the NFS server soon. The license will still be restrictive though

**Comment by julianxhokaxhiu** [comment]
May I ask why? Economical struggles? Have you considered other ways of funding like Patreon/Github Sponsors/etc.?

**Comment by d235j** [comment]
The license, as-is, is significantly more restrictive than that on macFUSE, as it prohibits all commercial use. With macFUSE, the license only applies to the software being redistributed (including via automatic download/installation).

At the very least, this restriction should be dropped, as "commercial use" can be interpreted very broadly. Hopefully in the future this software won't be necessary anymore.

**Comment by macos-fuse-t** [comment]
> The license, as-is, is significantly more restrictive than that on macFUSE, as it prohibits all commercial use. With macFUSE, the license only applies to the software being redistributed (including via automatic download/installation).
> 
> At the very least, this restriction should be dropped, as "commercial use" can be interpreted very broadly. Hopefully in the future this software won't be necessary anymore.

I actually only care about software vendors bundling the binaries under their own software or redistributing fuse-t packages. By bundling I mean taking fuse-t server, putting it under .app folder, re-signing everything. That would be the only two things the license aims to prevent doing for free. The license surely has to reflect this.

**Comment by jvican** [comment]
@macos-fuse-t Did you get to open sourcing the code of the NFS server yet? You mentioned you'd do it soon and I was curious to take a look at the source code.

**Comment by zi0Black** [comment]
Any update on this topic @macos-fuse-t? :)

**Comment by maxburke** [comment]
@macos-fuse-t looking at the disassembly of fuse-t 1.0.12 it seems like a number of files from the GPL/LGPL licensed libfuse are included in the fuse-t library; unfortunately this obligates you to release your source and modifications, or decouple entirely from libfuse. You cannot fork (L)GPL code, modify it, and incorporate it into your own restrictively licensed project.

The gist of the LGPL license is that I should be able to substitute my own copy of the LGPL licensed components -- in this case libfuse -- and it should be functionally identical.

**Comment by macos-fuse-t** [comment]
The project consists of two components: libfuse and fuse-t server. libfuse is LGPL licensed and can be downloaded from here: https://github.com/macos-fuse-t/libfuse. You can modify and build it as you wish, the build instructions are provided in the README file. The fuse-t server on the other hand is a proprietary component, it's written in go and doesn't link to or includes anything GPL related, all respective copyright owners are mentioned in License.txt file, so please stop your FUD or I'll ban you from posting here

**Comment by andreagrandi** [comment]
> I'm going to publish the source code of the NFS server soon. The license will still be restrictive though

I see the issue is marked as "closed/completed" but I can't find the "server" component anywhere. Where can we find the source code for it? Thanks

**Comment by fixcz** [comment]
> The project consists of two components: libfuse and fuse-t server. libfuse is LGPL licensed and can be downloaded from here: https://github.com/macos-fuse-t/libfuse. You can modify and build it as you wish, the build instructions are provided in the README file. The fuse-t server on the other hand is a proprietary component, it's written in go and doesn't link to or includes anything GPL related, all respective copyright owners are mentioned in License.txt file, so please stop your FUD or I'll ban you from posting here

I’m sorry, but your approach contradicts the basic principles of GitHub. I wouldn’t trust this software. I believe you could benefit more by making the code open. There are licenses that allow the community to contribute without you losing the right to sell the software.

Also, please stop being rude. If you look at the reactions to your comment, you’ll see that no one appreciates this approach.

fix

**Comment by nv6** [comment]
"I'lL bAn YoU fRoM pOsTinG" holy discord mod lmao touch grass
