### ISSUE TITLE
installer pkg puts headers in wrong directory on clean macOS install

### ISSUE THREAD

**Issue by djdv** [macos-fuse-t/fuse-t#10]
short version:
If you install the FUSE-T pkg while `/usr/local/include` does not exist, the fuse headers go directly into `/usr/local/include` rather than `/usr/local/include/fuse`.

long version:
This was hard to track down, but on a fresh install of macOS, I beleive `/usr/local` should be empty. Specifically `/usr/local/include` would not exist.
If you install the FUSE-T pkg while `/usr/local/include` does not exist, the fuse headers go directly into `/usr/local/include` rather than `/usr/local/include/fuse`.
Since the `uninstall.sh` script fails to remove these headers, I assume this is not intentional.
Creating `/usr/local/include` (either manually or by side effect of something else - like installing homebrew) prior to installing the package will not cause this problem.

Installing homebrew creates the `/usr/local/include` directory (at least on x86) which is why this problem will not occur when installing via homebrew using default settings like the documentation has on the FUSE-T website.

Worst of all, if you install the pkg without `/usr/local/include`, then run the uninstall script, then reinstall the pkg, you'll have the fuse headers in both directories.
Any of these combinations leads to inconsistencies across builders/machines in regard to compiler flags / include search paths.

Screencast of this being replicated: https://www.youtube.com/watch?v=NbaRN2PhJRw

**Comment by djdv** [comment]
Also worth mentioning the uninstaller leaves behind 2 archives within `/usr/local/lib` but does remove the dylibs.
Assuming this is also not intentional.

**Comment by macos-fuse-t** [comment]
Thanks for reporting, I will check and fix
