### ISSUE TITLE
Veracrypt not working with Fuse-T

### ISSUE THREAD

**Issue by seanieb** [macos-fuse-t/fuse-t#11]
When I try to install Veracrypt it doesn't recognize Fuse-T as being a Fuse implementation.  

https://www.veracrypt.fr/

**Comment by macos-fuse-t** [comment]
You should open a ticket with veracrypt. Unfortunately there's not much I can do about it.

**Comment by seanieb** [comment]
Will do. Just posted here just incase it was something that could be worked around on the Fuse-T end.

**Comment by macos-fuse-t** [comment]
I can confirm it will work with minor changes to veracrypt. I personally compiled and tested it a few weeks ago.Sent from my iPhoneOn 19 Nov 2022, at 14:14, Seanie Byrne ***@***.***> wrote:﻿
Closed #11 as completed.

**Comment by Mat-KH** [comment]
> I can confirm it will work with minor changes to veracrypt.

Would you be able to share these minor changes with the veracrypt project, e.g. as a PR?
As of now, about one and a half years later, this is still an open issue.

**Comment by macos-fuse-t** [comment]
Someone already asked for it so here it's:
https://github.com/macos-fuse-t/VeraCrypt
Keep in mind It's just a reference of what needs to be done and absolutely not tested. Unfortunately I don't have time to make further work on it.
