### ISSUE TITLE
pkg-config (fuse.pc) compatible files?

### ISSUE THREAD

**Issue by maxburke** [macos-fuse-t/fuse-t#12]
Hello!

Would it be possible to supply pkg-config compatible metadata files for fuse-t?

**Comment by macos-fuse-t** [comment]
Good point. I will include it for the next release

**Comment by macos-fuse-t** [comment]
Completed in 1.0.7

**Comment by maxburke** [comment]
Brilliant, thanks! I tried it and it works a treat.
