### ISSUE TITLE
1.0.7 will not run on Intel (go-nfsv4-1.0.7 is Apple Silicon only)

### ISSUE THREAD

**Issue by footlooseboss** [macos-fuse-t/fuse-t#13]
`fuse: failed to exec mount program: Bad CPU type in executable`

**Comment by macos-fuse-t** [comment]
The 1.0.7 package didn't include x86 version. Fixed in 1.0.8. Please reinstall.
Sorry about the mess

**Comment by footlooseboss** [comment]
life happens, cheers for fast response
