### ISSUE TITLE
mount_macfuse alternative

### ISSUE THREAD

**Issue by libor13** [macos-fuse-t/fuse-t#18]
In macFUSE there is mount_macfuse binary executable.
Is in fuse-t something similar ?

**Comment by macos-fuse-t** [comment]
You can see the communication details at https://github.com/macos-fuse-t/libfuse and https://github.com/macos-fuse-t/go-fuse

**Comment by libor13** [comment]
> You can see the communication details at https://github.com/macos-fuse-t/libfuse and https://github.com/macos-fuse-t/go-fuse

Great! We use macfuse in gocryptfs so it seems that it is what i am looking for, I will try it.
