### ISSUE TITLE
Files with emoji characters in their name makes the whole folder not show any files

### ISSUE THREAD

**Issue by aomizu** [macos-fuse-t/fuse-t#19]
Tested on 1.0.16 on macOS 13.2.1 (22D68)
rclone version v1.62.1 (encrypted)

How to reproduce:
- move or create a file in a folder
- add an emoji character (like 😺) in RcloneBrowser
- all content of the folder in Finder is now gone

fuse-t doesn't allow renaming a file with an emoji character in it, so I'm using RcloneBrowser.
since I had no issues with macfuse, I assume that fuse-t has trouble displaying emoji characters.

**Comment by macos-fuse-t** [comment]
have you looked at this:
https://github.com/macos-fuse-t/fuse-t/issues/16

**Comment by macos-fuse-t** [comment]
should be resolved
