### ISSUE TITLE
More install + uninstall info

### ISSUE THREAD

**Issue by rev111** [macos-fuse-t/fuse-t#2]
Hello, 
this sounds like a nice alternative to MacFuse. 
But what is its state, how long and well is it tested, is it production-ready?
What happens after I install? Can I see somewhere that it is working?
What happens if there is an existing MacFuse installation?
Finally, if I encounter a problem - how do I uninstall?

I couldn't find any information about that (sorry if I overlooked something).

**Comment by macos-fuse-t** [comment]
The first version (1.0.0) is not production ready yet.
The package itself is useless to the end user unless: you develop a filesystem based on FUSE, you install other packages that depend on it such as sshfs (which is conveniently attached to the downloads).
To uninstall run the following script: sudo "/Library/Application Support/fuse-t/uninstall.sh"
Finally you can install it along with macfuse.

**Comment by dirkpitt2050** [comment]
I managed to get it working with ntfs-3g (assuming fuse-t is installed already using homebrew):

1. Make sure autotools are installed (`brew install autoconf automake libtool`)
2. Download ntfs-3g source code: `git clone https://github.com/tuxera/ntfs-3g.git && cd ntfs-3g`
3. `autoreconf -i`
4. `./configure CFLAGS="-I/usr/local/include/fuse" LDFLAGS="-lintl -lfuse-t" FUSE_MODULE_CFLAGS="-I/usr/local/include/fuse -D_FILE_OFFSET_BITS=64" FUSE_MODULE_LIBS="-L/usr/local/lib"`
5. `make`
6. `sudo make install`
7. If make install aborts with error **mv: rename //usr/local/lib/libntfs-3g.so to //lib: No such file or directory**, finish install manually: `cp src/ntfs-3g /usr/local/bin; cp -R src/.libs /usr/local/bin`
8. Test ntfs-3g install, e.g.:
```sh
# unmount if necessary
sudo diskutil unmount /dev/disk1s1
# mount with ntfs-3g
sudo mkdir /Volumes/NTFS
sudo /usr/local/bin/ntfs-3g /dev/disk1s1 /Volumes/NTFS -o local -o allow_other -o auto_xattr -o auto_cache
```
9. This should result in an NFS mount named "localhost" that is ejectable in the Finder.
