### ISSUE TITLE
NTFS and exFAT drivers

### ISSUE THREAD

**Issue by albertputinjobs** [macos-fuse-t/fuse-t#20]
can you make a ntfs and exfat driver like tuxera or paragon plz

**Comment by macos-fuse-t** [comment]
you can compile it yourself: https://github.com/macos-fuse-t/ntfs-3g

**Comment by albertputinjobs** [comment]
It is too confusing why don't use make your own ntfs driver and sell it on
mac app store for ntfs and exfat

**Comment by macos-fuse-t** [comment]
as you mentioned there are available solutions. why do you need another one?

**Comment by albertputinjobs** [comment]
because those are not working when they ask to enable kext in settings they
are not showing up.

there is no available solution without enabling kext in settings and they
are not showing up even if they do show up it asks to restart and when I
did it does not work!

**Comment by albertputinjobs** [comment]
It is not mounting drives 
<img width="1728" alt="Screenshot 2023-05-01 at 10 37 01 AM" src="https://user-images.githubusercontent.com/57960893/235409641-20deb3a5-ba19-430d-9df3-00d468a0edd4.png">

**Comment by macos-fuse-t** [comment]
Did you create a mount point first (/Volumes/CCC....) ?

**Comment by albertputinjobs** [comment]
can u help me how to do that ?

**Comment by Rastafabisch** [comment]
I'm having trouble compiling the NTFS driver as well – during the `make install `stage:
```
if [ ! "/lib" -ef "/usr/local/lib" ]; then \
		/bin/mv -f "//usr/local/lib"/libntfs-3g.so* "//lib";  \
	fi
mv: rename //usr/local/lib/libntfs-3g.so* to //lib: No such file or directory
```

Could you provide a homebrew formula for nfs-3g as well?

**Comment by Rastafabisch** [comment]
I fixed it by appending `--exec_prefix=/opt…` to the `./configure `command.

**Comment by albertputinjobs** [comment]
can u make a video are u able to mount ?

**Comment by asamahy** [comment]
@albertputinjobs 

1. download or clone the repository
2. using terminal cd inside the ntfs-3g directory
3. run the following commands one by one: (assuming you already installed FUSE-T)
```
./autogen
LDFLAGS="-L/usr/local/lib -lintl" ./configure --with-fuse=/usr/local/lib/libfuse-t.dylib --prefix=/usr/local --mandir=/usr/local/share/man --exec_prefix=/usr/local
make
make install
```
4. and to mount a drive:
`sudo ntfs-3g /dev/DISK-LOCATION /Volumes/MOUNT-NAME`
if it complains about not finding the mount point then create it first using mkdir:
`sudo mkdir /Volumes/MOUNT-NAME`

P.S: change DISK-LOCATION and MOUNT-NAME with your corresponding one. you can find you disk location using `diskutil list`

**Comment by albertputinjobs** [comment]
this technology works but it is very slow read write speed it is taking lot of minutes. iboysoft ntfs is much faster than this

**Comment by asamahy** [comment]
Slow yet is completely free.
btw iboysoft does make at least 3 false claims about ntfs-3g
1) it does support Ventura.
2) it does support automount.
3) and it can repair NTFS disks.

anyways this is not a who done it better thread, you asked how to compile and use for NTFS drives and an answer was provided hopefully with an easy to follow steps.

**Comment by AhmedYasinKUL** [comment]
> @albertputinjobs
> 
> 1. download or clone the repository
> 2. using terminal cd inside the ntfs-3g directory
> 3. run the following commands one by one: (assuming you already installed FUSE-T)
> 
> ```
> ./autogen
> LDFLAGS="-L/usr/local/lib -lintl" ./configure --with-fuse=/usr/local/lib/libfuse-t.dylib --prefix=/usr/local --mandir=/usr/local/share/man --exec_prefix=/usr/local
> make
> make install
> ```
> 
> 4. and to mount a drive:
>    `sudo ntfs-3g /dev/DISK-LOCATION /Volumes/MOUNT-NAME`
>    if it complains about not finding the mount point then create it first using mkdir:
>    `sudo mkdir /Volumes/MOUNT-NAME`
> 
> P.S: change DISK-LOCATION and MOUNT-NAME with your corresponding one. you can find you disk location using `diskutil list`

It doesn't work for me since it could not find libintl file. To solve this, I used:
`
LDFLAGS="-L/usr/local/lib -L/opt/homebrew/Cellar/gettext/0.22.3/lib/ -lintl" ./configure --with-fuse=/usr/local/lib/libfuse-t.dylib --prefix=/usr/local --mandir=/usr/local/share/man --exec_prefix=/usr/local
`

It worked for me but now, `sudo ntfs-3g` command gives an error like:

`
dyld[49668]: Symbol not found: _fuse_destroy
  Referenced from: <E48335E1-6AC2-3104-84AC-4218ABAFA84F> /usr/local/bin/ntfs-3g
  Expected in:     <no uuid> unknown
zsh: abort      sudo ntfs-3g
`

Do you have any idea about that? I am running MacOS Ventura.

**Comment by AhmedYasinKUL** [comment]
> Is /usr/local/bin/ntfs-3g a correct binary? What is the output of `otool -L /usr/local/bin/ntfs-3g`

Here is the output:
```
otool -L /usr/local/bin/ntfs-3g
/usr/local/bin/ntfs-3g:
	@rpath/libfuse-t.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libntfs-3g.89.dylib (compatibility version 90.0.0, current version 90.0.0)
	/opt/homebrew/opt/gettext/lib/libintl.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 2048.1.255)
```

**Comment by macos-fuse-t** [comment]
`sudo install_name_tool -add_rpath /usr/local/lib /usr/local/bin/ntfs-3g`

**Comment by albertputinjobs** [comment]
autogen errors:


z@Zs-MacBook-Pro ntfs-3g-edge % sh autogen.sh
Running autoreconf --verbose --install --force
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:329: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy --force
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
glibtoolize: Remember to add 'LT_INIT' to configure.ac.
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: aclocal --force -I m4
configure.ac:329: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
autoreconf: running: /opt/homebrew/Cellar/autoconf/2.71/bin/autoconf --force
configure.ac:189: warning: The macro `AC_GNU_SOURCE' is obsolete.
configure.ac:189: You should run autoupdate.
./lib/autoconf/specific.m4:312: AC_GNU_SOURCE is expanded from...
configure.ac:189: the top level
configure.ac:467: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:467: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:467: the top level
configure.ac:246: error: possibly undefined macro: AC_MSG_ERROR
   If this token and others are legitimate, please use m4_pattern_allow.
   See the Autoconf documentation.
configure.ac:329: error: possibly undefined macro: AM_PATH_LIBGCRYPT
configure.ac:334: error: possibly undefined macro: AC_MSG_WARN
autoreconf: error: /opt/homebrew/Cellar/autoconf/2.71/bin/autoconf failed with exit status: 1

**Comment by albertputinjobs** [comment]
fixed above with brew install libgcrypt and brew install gcc

**Comment by albertputinjobs** [comment]
I got fuse.h error and this fixes it ./configure --exec-prefix=/usr/local && make && sudo make install

**Comment by albertputinjobs** [comment]
and then using rpath command and then finally works

**Comment by albertputinjobs** [comment]
<img width="1728" alt="Screenshot 2023-12-17 at 12 45 56 PM" src="https://github.com/macos-fuse-t/fuse-t/assets/57960893/14e87b78-80bb-4a6f-b2d1-530ede3476e6">

How to fix invalid file system ?  I did create mount point with mkdir

**Comment by macos-fuse-t** [comment]
isn't it /dev/disk15s2 ?

**Comment by albertputinjobs** [comment]
I tried that earlier before did not work

**Comment by albertputinjobs** [comment]
I freshly formatted a pendrive in windows ntfs and I tried it again with new mkdir and after the mount command same error invalid file system 
<img width="1728" alt="Screenshot 2023-12-17 at 3 37 42 PM" src="https://github.com/macos-fuse-t/fuse-t/assets/57960893/a73b624c-9e82-49fa-b56d-39f3fa30550f">

**Comment by albertputinjobs** [comment]
I just created a folder and dragged it into the NTFS-3g command (sudo ntfs-3g /dev/disk5s2 /Users/z/untitled\ folder )
finally it worked but it is very very slow to use it for any real use.


<img width="1728" alt="Screenshot 2023-12-17 at 4 16 35 PM" src="https://github.com/macos-fuse-t/fuse-t/assets/57960893/69747432-27c0-450f-8694-da072cfc1777">


Thanks for creating this amazing software anyways!

**Comment by Akczht** [comment]
can someone provide build instructions for m1 macs i'm struggling to compile ntfs-3g

**Comment by Akczht** [comment]
```
s_3g-lowntfs-3g.o lowntfs_3g-ntfs-3g_common.o  -L/usr/local/lib ../libntfs-3g/.libs/libntfs-3g.dylib -lintl -lc -framework CoreFoundation
Undefined symbols for architecture arm64:
  "_fuse_destroy", referenced from:
      _main in ntfs_3g-ntfs-3g.o
      _mount_fuse in ntfs_3g-ntfs-3g.o
  "_fuse_get_context", referenced from:
      _ntfs_close in ntfs_3g-ntfs-3g.o
      _ntfs_fuse_getattr in ntfs_3g-ntfs-3g.o
      _ntfs_fuse_chmod in ntfs_3g-ntfs-3g.o
      _ntfs_fuse_chown in ntfs_3g-ntfs-3g.o
      _ntfs_fuse_setxattr in ntfs_3g-ntfs-3g.o
      _ntfs_fuse_getxattr in ntfs_3g-ntfs-3g.o
      _ntfs_fuse_removexattr in ntfs_3g-ntfs-3g.o
      ...
  "_fuse_get_session", referenced from:
      _mount_fuse in ntfs_3g-ntfs-3g.o
  "_fuse_loop", referenced from:
      _main in ntfs_3g-ntfs-3g.o
  "_fuse_mount", referenced from:
      _mount_fuse in ntfs_3g-ntfs-3g.o
  "_fuse_new", referenced from:
      _mount_fuse in ntfs_3g-ntfs-3g.o
  "_fuse_opt_add_arg", referenced from:
      _mount_fuse in ntfs_3g-ntfs-3g.o
      _mount_fuse in ntfs_3g-ntfs-3g.o
      _mount_fuse in ntfs_3g-ntfs-3g.o
      _mount_fuse in ntfs_3g-ntfs-3g.o
      _mount_fuse in ntfs_3g-ntfs-3g.o
      _mount_fuse in ntfs_3g-ntfs-3g.o
  "_fuse_opt_free_args", referenced from:
      _mount_fuse in ntfs_3g-ntfs-3g.o
      _mount_fuse in ntfs_3g-ntfs-3g.o
  "_fuse_set_signal_handlers", referenced from:
      _mount_fuse in ntfs_3g-ntfs-3g.o
  "_fuse_unmount", referenced from:
      _main in ntfs_3g-ntfs-3g.o
      _mount_fuse in ntfs_3g-ntfs-3g.o
  "_fuse_version", referenced from:
      _main in ntfs_3g-ntfs-3g.o
      _usage in ntfs_3g-ntfs-3g.o
      _setup_logging in ntfs_3g-ntfs-3g.o
      _ntfs_parse_options in ntfs_3g-ntfs-3g_common.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ntfs-3g] Error 1
make[2]: *** Waiting for unfinished jobs....
Undefined symbols for architecture arm64:
  "_fuse_add_direntry", referenced from:
      _ntfs_fuse_filler in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_filler in lowntfs_3g-lowntfs-3g.o
  "_fuse_lowlevel_new", referenced from:
      _mount_fuse in lowntfs_3g-lowntfs-3g.o
  "_fuse_lowlevel_notify_inval_inode", referenced from:
      _ntfs_fuse_setxattr in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_removexattr in lowntfs_3g-lowntfs-3g.o
  "_fuse_mount", referenced from:
      _mount_fuse in lowntfs_3g-lowntfs-3g.o
  "_fuse_opt_add_arg", referenced from:
      _mount_fuse in lowntfs_3g-lowntfs-3g.o
      _mount_fuse in lowntfs_3g-lowntfs-3g.o
      _mount_fuse in lowntfs_3g-lowntfs-3g.o
      _mount_fuse in lowntfs_3g-lowntfs-3g.o
      _mount_fuse in lowntfs_3g-lowntfs-3g.o
  "_fuse_opt_free_args", referenced from:
      _mount_fuse in lowntfs_3g-lowntfs-3g.o
      _mount_fuse in lowntfs_3g-lowntfs-3g.o
  "_fuse_remove_signal_handlers", referenced from:
      _main in lowntfs_3g-lowntfs-3g.o
  "_fuse_reply_attr", referenced from:
      _ntfs_fuse_getattr in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_setattr in lowntfs_3g-lowntfs-3g.o
  "_fuse_reply_bmap", referenced from:
      _ntfs_fuse_bmap in lowntfs_3g-lowntfs-3g.o
  "_fuse_reply_buf", referenced from:
      _ntfs_fuse_read in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_readdir in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_readdir in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_getxattr in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_getxattr in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_listxattr in lowntfs_3g-lowntfs-3g.o
  "_fuse_reply_create", referenced from:
      _ntfs_fuse_create_file in lowntfs_3g-lowntfs-3g.o
  "_fuse_reply_entry", referenced from:
      _ntfs_fuse_lookup in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_mknod in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_mkdir in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_symlink in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_link in lowntfs_3g-lowntfs-3g.o
  "_fuse_reply_err", referenced from:
      _ntfs_fuse_lookup in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_getattr in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_setattr in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_readlink in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_mknod in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_mkdir in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_unlink in lowntfs_3g-lowntfs-3g.o
      ...
  "_fuse_reply_ioctl", referenced from:
      _ntfs_fuse_ioctl in lowntfs_3g-lowntfs-3g.o
  "_fuse_reply_open", referenced from:
      _ntfs_fuse_open in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_opendir in lowntfs_3g-lowntfs-3g.o
  "_fuse_reply_readlink", referenced from:
      _ntfs_fuse_readlink in lowntfs_3g-lowntfs-3g.o
  "_fuse_reply_statfs", referenced from:
      _ntfs_fuse_statfs in lowntfs_3g-lowntfs-3g.o
  "_fuse_reply_write", referenced from:
      _ntfs_fuse_write in lowntfs_3g-lowntfs-3g.o
  "_fuse_reply_xattr", referenced from:
      _ntfs_fuse_getxattr in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_getxattr in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_listxattr in lowntfs_3g-lowntfs-3g.o
  "_fuse_req_ctx", referenced from:
      _ntfs_fuse_newlink in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_lookup in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_getattr in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_setattr in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_opendir in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_setxattr in lowntfs_3g-lowntfs-3g.o
      _ntfs_fuse_getxattr in lowntfs_3g-lowntfs-3g.o
      ...
  "_fuse_session_add_chan", referenced from:
      _mount_fuse in lowntfs_3g-lowntfs-3g.o
  "_fuse_session_destroy", referenced from:
      _main in lowntfs_3g-lowntfs-3g.o
      _mount_fuse in lowntfs_3g-lowntfs-3g.o
  "_fuse_session_loop", referenced from:
      _main in lowntfs_3g-lowntfs-3g.o
  "_fuse_set_signal_handlers", referenced from:
      _mount_fuse in lowntfs_3g-lowntfs-3g.o
  "_fuse_unmount", referenced from:
      _main in lowntfs_3g-lowntfs-3g.o
      _mount_fuse in lowntfs_3g-lowntfs-3g.o
  "_fuse_version", referenced from:
      _main in lowntfs_3g-lowntfs-3g.o
      _usage in lowntfs_3g-lowntfs-3g.o
      _setup_logging in lowntfs_3g-lowntfs-3g.o
      _ntfs_parse_options in lowntfs_3g-ntfs-3g_common.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lowntfs-3g] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by Akczht** [comment]
here's my configure command
`LDFLAGS="-L/usr/local/lib -lintl" FUSE_MODULE_CFLAGS="-D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse" ./configure --with-fuse=/usr/local/lib/libfuse-t.dylib --disable-debug --exec-prefix=/usr/local`

**Comment by Akczht** [comment]
here's my [base](https://gist.github.com/Akczht/62bbf1f449347e541405becae75a1a3f#file-base-sh) build script for dependencies

**Comment by albertputinjobs** [comment]
This is my effort with all errors fixing and if u can then make sense out of it or else just use mounty for mac.

https://drive.google.com/file/d/13v0mhG5yv2_VAcjbWBetlaXYbYy-zgwL/view?usp=sharing
https://send.now/gf7uou341lin

**Comment by albertputinjobs** [comment]
I made a pkg might work for you 

https://drive.google.com/file/d/1q39pvrLj2PEfazP9jMh6Vz41tV4qrr4s/view?usp=sharing
https://www.dropbox.com/scl/fi/v2u1bkyky415yl293ozma/ntfs-3g-1.0.pkg?rlkey=wh4wbsukkpqf2fg7xujdvdorl&st=ac0aohh5&dl=0
