### ISSUE TITLE
Virustotal false positive ?

### ISSUE THREAD

**Issue by Davelortenco** [macos-fuse-t/fuse-t#21]
in Virustotal.com 1 out of 86 antivirus detects a malware on latest release 1.0.17:

https://www.virustotal.com/gui/url/8dee4585deda99fc1b49f6d56da915dfa5111661dd48e7512d30efa095f17d03
![image](https://user-images.githubusercontent.com/97322786/227748181-93e07edb-8603-4249-adad-20b01872f1a0.png)

1- Is it a false positive ?
2- If it is, how to solve it because this warning will prevent many people from using fuse-T that is intended to manage filesystems.

**Comment by macos-fuse-t** [comment]
I can assure you fuse-t is not a malware. If that bothers you, contact them directly and try getting more details.
