### ISSUE TITLE
Way to check fuse-t version

### ISSUE THREAD

**Issue by PeacheyMcKeitch** [macos-fuse-t/fuse-t#24]
Hi all, was wondering if there is a way to check which version of Fuse-t you have installed? For checking for updates and the like. 

Had a look in the logs as well and didn't see any version no hints. 

(For installing with the pkg not with brew that is.)

Keep up the good work!

**Comment by macos-fuse-t** [comment]
you can use either
"pkgutil --pkgs|grep fuse-t" and "pkgutil --pkg-info ..."
or "ls -al /Library/Application\ Support/fuse-t/bin/go-nfsv4". it should point to go-nfsv4-$(VERSION)
