### ISSUE TITLE
NFS local server name

### ISSUE THREAD

**Issue by libor13** [macos-fuse-t/fuse-t#25]
Is possible to change name of NFS localhost server? By default name is localhost.

**Comment by alexfs** [comment]
It should be possible to change it to the local machine hostname. Why does it matter though?

**Comment by libor13** [comment]
We used fuse-t with go crypts. When we create virtual drive, it is displayed in Finder "locations" section, but it is inside "localhost". It can be confusing for users to find this virtual disk.

![image](https://user-images.githubusercontent.com/51494002/234793320-9f188d72-4520-49f5-86ab-64da41834703.png)

**Comment by macos-fuse-t** [comment]
What do you expect to be less confusing?

**Comment by libor13** [comment]
To be able to change the name of the local server.
Common user don't know what is localhost.

**Comment by macos-fuse-t** [comment]
Resolved in the 1.0.22
