### ISSUE TITLE
File size limitation

### ISSUE THREAD

**Issue by ceilingfan3521** [macos-fuse-t/fuse-t#26]
Is there a file size limitation imposed by FUSE-T (or NFS)? This is a video of Cryptomator using FUSE-T…
https://www.reddit.com/r/Cryptomator/comments/13kd682/only_happens_with_bigger_files/

**Comment by macos-fuse-t** [comment]
100mb is not a large file. Please check what error -36 means in cryptomator. It could be not enough disk space left.Sent from my iPhoneOn 19 May 2023, at 13:36, ceilingfan3521 ***@***.***> wrote:﻿
Is there a file size limitation imposed by FUSE-T (or NFS)? This is a video of Cryptomator using FUSE-T…
https://www.reddit.com/r/Cryptomator/comments/13kd682/only_happens_with_bigger_files/

**Comment by macos-fuse-t** [comment]
couldn't reproduce
