### ISSUE TITLE
local disk cache performanace

### ISSUE THREAD

**Issue by sharkopen** [macos-fuse-t/fuse-t#27]
When using a local disk as cache, what options should be set for Fuse-t to achieve similar read/write performance as the local disk?

**Comment by macos-fuse-t** [comment]
You can try playing with rwsize: -o rwsize=262144

**Comment by macos-fuse-t** [comment]
What is your use case?

**Comment by sharkopen** [comment]
Some tasks or job files are located on a remote server and need to be accessed using local software. To facilitate the operation and reduce manual file copying to the local machine, it is desired to directly use local software to read and write the task files at the mount point. If the read/write performance is not similar to local disk cache, executing tasks involving large files will still take a considerable amount of time.

**Comment by sharkopen** [comment]
use intranet with remote-server

**Comment by macos-fuse-t** [comment]
If it's for a commercial project, contact me directly by e-mail. surely performance can be tweaked but it's not an urgent issue at this moment
