### ISSUE TITLE
Unable to specify volume icon

### ISSUE THREAD

**Issue by PKizzle** [macos-fuse-t/fuse-t#28]
I cannot mount a volume when specifying a custom volume icon using `-o volicon=${ICNS_PATH}`.
It should mount the volume using the specified icns file as documented [here](https://github.com/osxfuse/osxfuse/wiki/Mount-options#volicon).

For reference I have falsely opened an [issue](https://github.com/cryptomator/cryptomator/issues/2979) over at the cryptomator project.

**Comment by macos-fuse-t** [comment]
This functionality is not supported

**Comment by PKizzle** [comment]
Is this a limitation of how NFS drives are handled by macOS?

**Comment by macos-fuse-t** [comment]
Yes it is

**Comment by PKizzle** [comment]
Ok, then I will close this issue
