### ISSUE TITLE
homebrew formula support

### ISSUE THREAD

**Issue by benjioh5** [macos-fuse-t/fuse-t#3]
I think adding this project to homebrew cask formula is needed.

**Comment by macos-fuse-t** [comment]
That would be a great idea, hope someone will pick it up...

**Comment by macos-fuse-t** [comment]
Added btw, I need to wait 30 days before submitting it into the official brew repo though.

**Comment by macos-fuse-t** [comment]
done

**Comment by slonopotamus** [comment]
But... Where is it?

**Comment by benjioh5** [comment]
@slonopotamus https://github.com/macos-fuse-t/homebrew-cask maybe this?
