### ISSUE TITLE
Unable to listen to unix domain socket inside bindfs mount

### ISSUE THREAD

**Issue by slonopotamus** [macos-fuse-t/fuse-t#31]
`binfs` build instructions: https://github.com/mpartel/bindfs/issues/100#issuecomment-1627767719

Minimal way to reproduce:

(as root)

```
$ mkdir a
$ mkdir b
$ bindfs a b
$ nc -U b/sock -l
nc: Input/output error
$ nc -U a/sock -l
<works>
```

My environment: macOS Ventura + fuse-t 1.0.23 + bindfs 1.17.3

Note that the same steps do work on Linux + [netcat-openbsd](https://salsa.debian.org/debian/netcat-openbsd).

`bindfs` devs believe the root of the issue is _not_ in bindfs itself: https://github.com/mpartel/bindfs/issues/132#issuecomment-1630373952

`nc` is just used as an example (it is installed on macOS out of the box), I observe the same behavior when trying to listen to unix domain socket from Go via `net.Listen("unix", path.Join("b/sock")`

**Comment by slonopotamus** [comment]
See additional details in https://github.com/mpartel/bindfs/issues/132. It _looks_ like fuse-t doesn't forward `mknod` call to bindfs at all.

**Comment by alexfs** [comment]
bindfs doesn't implement mknod with sock file type.
See https://libfuse.github.io/doxygen/example_2passthrough__helpers_8h_source.html

**Comment by slonopotamus** [comment]
Yeah, but if I read log correctly, fuse-t doesn't even _try_ to call `mknod` in bindfs?

**Comment by slonopotamus** [comment]
I've tried 1.0.24, but it seems that fuse-t still doesn't pass `mknod` call to binds

Running `bindfs -d -f` shows that `nc -U sock -l` produces the following calls:

```
unique: 50, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 0
getattr /
   unique: 50, success, outsize: 136
unique: 51, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 0
statfs_x /
   unique: 51, success, outsize: 96
unique: 52, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 0
statfs_x /
   unique: 52, success, outsize: 96
unique: 53, opcode: LOOKUP (1), nodeid: 1, insize: 42, pid: 0
LOOKUP /b
getattr /b
   unique: 53, error: -2 (No such file or directory), outsize: 16
unique: 54, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 0
statfs_x /
   unique: 54, success, outsize: 9
```

**Comment by alexfs** [comment]
bindfs -d -f a b
nc -U -l b/sock1

statfs_x /
   unique: 55, success, outsize: 96
unique: 56, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 0
getattr /
   unique: 56, success, outsize: 136
unique: 57, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 0
LOOKUP /sock1
getattr /sock1
   unique: 57, error: -2 (No such file or directory), outsize: 16
unique: 58, opcode: MKNOD (8), nodeid: 1, insize: 62, pid: 0
mknod /sock1 0140755 0x0 umask=0000

**Comment by slonopotamus** [comment]
Hmm... Not sure what I did wrong. After retrying, I confirm that `mknod` is now passed to binds. `nc` is still unable to create UNIX socket, but as was discussed, this needs to be fixed on binds side. Thanks for the fix.
