### ISSUE TITLE
ERROR: Permission Denied when moving file to fuse-t mount point.

### ISSUE THREAD

**Issue by engaineer** [macos-fuse-t/fuse-t#42]
__OS__
macOS Sonoma 14.1

__Fuse-T__
fuse-t (1.0.31) installed with homebrew.

**Other Software**
Cryptomator 1.10.1 (dmg-4844)

**Steps to Reproduce**
1. Create a Cryptomator vault: TestVault, unlock and mount.
2. Verify vault mounted under NFS mount fuse-t > TestVault
3. Open a PDF file from logged in user's Downloads folder with Preview/Pages etc
4. Select the TestVault which is mounted by fuse-t:
- Click on the filename to display the "Name: Tags: Where:" box. Under the 'Where:; dropdown change the folder from 'Downloads' to 'TestVault' (or any folder inside the TestVault)
- Click File -> Move to ... and select TestVault
5. Error Message received of:
"Document.pdf" couldn't be moved because you don't have permission to access
"TestVault". 
![Screenshot of Error Message](https://github.com/macos-fuse-t/fuse-t/assets/25338643/bfb19db9-fd97-4fa6-ba02-9a08defb43e6)

**Expected result**:
The file is moved to the chosen folder without error.

**Debug Logs Extract**
8:46:20.215 [JavaFX Application Thread] INFO o.c.ui.unlock.UnlockWorkflow - Unlock of 'TestVault' succeeded.
18:47:28.514 [JavaFX Application Thread] DEBUG org.cryptomator.logging.DebugMode - Debug mode enabled
18:47:29.518 [App Scheduled Executor 02] DEBUG o.c.common.settings.SettingsProvider - Attempting to save settings to /Users/neuralflux/Library/Application Support/Cryptomator/settings.json
18:47:29.522 [App Scheduled Executor 02] INFO o.c.common.settings.SettingsProvider - Settings saved to /Users/neuralflux/Library/Application Support/Cryptomator/settings.json
18:47:35.257 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:35.258 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2023-11-05T07:46:37.947902224Z, lastAccessTime: 2023-11-05T07:46:37.947902641Z, creationTime: 2023-11-05T07:46:15Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 128, fileKey: (dev=1000010,ino=87140195))
18:47:35.260 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:35.260 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:35.261 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:35.263 [Thread-21] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2023-11-05T06:56:11.004053766Z, lastAccessTime: 2023-11-05T06:56:11.490250336Z, creationTime: 2023-08-13T04:24:52Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 640, fileKey: (dev=1000010,ino=79478948))
18:47:35.264 [Thread-19] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:35.264 [Thread-22] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:35.265 [Thread-12] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:35.307 [Thread-10] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Receipts & Bills (lastModifiedTime: 2023-11-05T07:41:28.163595402Z, lastAccessTime: 2023-11-05T07:47:35.307629917Z, creationTime: 2023-08-14T12:01:36Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 1184, fileKey: (dev=1000010,ino=79787680))
18:47:40.663 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:40.666 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2023-11-05T07:46:37.947902224Z, lastAccessTime: 2023-11-05T07:46:37.947902641Z, creationTime: 2023-11-05T07:46:15Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 128, fileKey: (dev=1000010,ino=87140195))
18:47:40.667 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:40.670 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:40.673 [Thread-17] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:40.674 [Thread-11] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2023-11-05T06:56:11.004053766Z, lastAccessTime: 2023-11-05T06:56:11.490250336Z, creationTime: 2023-08-13T04:24:52Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 640, fileKey: (dev=1000010,ino=79478948))
18:47:40.741 [Thread-9] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:46.797 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:46.798 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2023-11-05T07:46:37.947902224Z, lastAccessTime: 2023-11-05T07:46:37.947902641Z, creationTime: 2023-11-05T07:46:15Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 128, fileKey: (dev=1000010,ino=87140195))
18:47:46.799 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:47.082 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:47.083 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf failed, node not found
18:47:47.101 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:47.102 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:47.103 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf failed, node not found
18:47:47.103 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:47.104 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf failed, node not found
18:47:47.104 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:47.104 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf failed, node not found
18:47:47.105 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:47.105 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf failed, node not found
18:47:47.105 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:47.106 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:47.106 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf failed, node not found
18:47:47.107 [Thread-23] TRACE o.c.frontend.fuse.ReadWriteAdapter - create /Document.pdf with flags [READ, WRITE, CREATE]
18:47:47.108 [Thread-23] TRACE o.c.cryptofs.fh.FileHeaderHolder - Generating file header for /Users/neuralflux/tmp/TestVault/d/SY/3WIATL5RDSUP3HJAWUSXYFERDDMCND/jJP2t3JUkG14nSQ6Nme8oZe66NLcskwYKcPwPQ==.c9r
18:47:47.108 [Thread-23] TRACE o.c.cryptofs.fh.OpenCryptoFile - First channel for this openFile. Initializing file size...
18:47:47.108 [Thread-23] TRACE o.c.frontend.fuse.OpenFileFactory - Opening 5 OpenFile{path=/Document.pdf, channel=org.cryptomator.cryptofs.ch.CleartextFileChannel@36bd5829}
18:47:47.109 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf (lastModifiedTime: 2023-11-05T07:47:47.108772Z, lastAccessTime: 2023-11-05T07:47:47.109227Z, creationTime: 2023-11-05T07:47:47Z, isRegularFile: true, isDirectory: false, isSymbolicLink: false, isOther: false, size: 0, fileKey: (dev=1000010,ino=87140413))
18:47:47.109 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2023-11-05T07:47:47.108144062Z, lastAccessTime: 2023-11-05T07:46:37.947902641Z, creationTime: 2023-11-05T07:46:15Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 160, fileKey: (dev=1000010,ino=87140195))
18:47:47.110 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf (lastModifiedTime: 2023-11-05T07:47:47.108772Z, lastAccessTime: 2023-11-05T07:47:47.11048Z, creationTime: 2023-11-05T07:47:47Z, isRegularFile: true, isDirectory: false, isSymbolicLink: false, isOther: false, size: 0, fileKey: (dev=1000010,ino=87140413))
18:47:47.111 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:47.112 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf (lastModifiedTime: 2023-11-05T07:47:47.108772Z, lastAccessTime: 2023-11-05T07:47:47.112086Z, creationTime: 2023-11-05T07:47:47Z, isRegularFile: true, isDirectory: false, isSymbolicLink: false, isOther: false, size: 0, fileKey: (dev=1000010,ino=87140413))
18:47:47.112 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:47.114 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - release /Document.pdf (5)
18:47:47.115 [Thread-23] TRACE o.c.frontend.fuse.OpenFileFactory - Releasing 5 OpenFile{path=/Document.pdf, channel=org.cryptomator.cryptofs.ch.CleartextFileChannel@36bd5829}
18:47:47.115 [Thread-23] TRACE o.c.cryptofs.ch.CleartextFileChannel - org.cryptomator.cryptofs.ch.CleartextFileChannel@36bd5829 - Writing file header.
18:47:47.116 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf (lastModifiedTime: 2023-11-05T07:47:47.108772Z, lastAccessTime: 2023-11-05T07:47:47.115642Z, creationTime: 2023-11-05T07:47:47Z, isRegularFile: true, isDirectory: false, isSymbolicLink: false, isOther: false, size: 0, fileKey: (dev=1000010,ino=87140413))
18:47:47.117 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf (lastModifiedTime: 2023-11-05T07:47:47.108772Z, lastAccessTime: 2023-11-05T07:47:47.115642Z, creationTime: 2023-11-05T07:47:47Z, isRegularFile: true, isDirectory: false, isSymbolicLink: false, isOther: false, size: 0, fileKey: (dev=1000010,ino=87140413))
18:47:47.118 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857803776 / 494384795648)
18:47:47.119 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf (lastModifiedTime: 2023-11-05T07:47:47.108772Z, lastAccessTime: 2023-11-05T07:47:47.115642Z, creationTime: 2023-11-05T07:47:47Z, isRegularFile: true, isDirectory: false, isSymbolicLink: false, isOther: false, size: 0, fileKey: (dev=1000010,ino=87140413))
18:47:47.120 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857803776 / 494384795648)
18:47:47.120 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf (lastModifiedTime: 2023-11-05T07:47:47.108772Z, lastAccessTime: 2023-11-05T07:47:47.115642Z, creationTime: 2023-11-05T07:47:47Z, isRegularFile: true, isDirectory: false, isSymbolicLink: false, isOther: false, size: 0, fileKey: (dev=1000010,ino=87140413))
18:47:47.121 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf (lastModifiedTime: 2023-11-05T07:47:47.108772Z, lastAccessTime: 2023-11-05T07:47:47.115642Z, creationTime: 2023-11-05T07:47:47Z, isRegularFile: true, isDirectory: false, isSymbolicLink: false, isOther: false, size: 0, fileKey: (dev=1000010,ino=87140413))
18:47:47.121 [Thread-25] TRACE o.c.frontend.fuse.ReadWriteAdapter - unlink /Document.pdf
18:47:47.122 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2023-11-05T07:47:47.122131806Z, lastAccessTime: 2023-11-05T07:46:37.947902641Z, creationTime: 2023-11-05T07:46:15Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 128, fileKey: (dev=1000010,ino=87140195))
18:47:47.122 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:47.123 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58857807872 / 494384795648)
18:47:47.123 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Document.pdf failed, node not found
18:48:06.180 [Thread-16] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2023-11-05T06:56:11.004053766Z, lastAccessTime: 2023-11-05T06:56:11.490250336Z, creationTime: 2023-08-13T04:24:52Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 640, fileKey: (dev=1000010,ino=79478948))
18:48:06.207 [Thread-18] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58855473152 / 494384795648)
18:48:06.208 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58855473152 / 494384795648)
18:48:06.209 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2023-11-05T07:47:47.122131806Z, lastAccessTime: 2023-11-05T07:46:37.947902641Z, creationTime: 2023-11-05T07:46:15Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 128, fileKey: (dev=1000010,ino=87140195))
18:48:06.210 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58855473152 / 494384795648)
18:48:06.211 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr /Applications failed, node not found
18:48:32.692 [Thread-21] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58855718912 / 494384795648)
18:48:32.693 [Thread-19] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2023-11-05T06:56:11.004053766Z, lastAccessTime: 2023-11-05T06:56:11.490250336Z, creationTime: 2023-08-13T04:24:52Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 640, fileKey: (dev=1000010,ino=79478948))
18:48:32.693 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58855718912 / 494384795648)
18:48:32.694 [Thread-23] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2023-11-05T07:47:47.122131806Z, lastAccessTime: 2023-11-05T07:46:37.947902641Z, creationTime: 2023-11-05T07:46:15Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 128, fileKey: (dev=1000010,ino=87140195))
18:48:35.679 [Thread-22] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58853437440 / 494384795648)
18:48:35.679 [Thread-12] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2023-11-05T06:56:11.004053766Z, lastAccessTime: 2023-11-05T06:56:11.490250336Z, creationTime: 2023-08-13T04:24:52Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 640, fileKey: (dev=1000010,ino=79478948))
18:48:35.680 [Thread-24] TRACE o.c.frontend.fuse.ReadOnlyAdapter - statfs / (58853437440 / 494384795648)
18:48:35.681 [Thread-25] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2023-11-05T07:47:47.122131806Z, lastAccessTime: 2023-11-05T07:46:37.947902641Z, creationTime: 2023-11-05T07:46:15Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 128, fileKey: (dev=1000010,ino=87140195))
18:48:41.561 [JavaFX Application Thread] DEBUG org.cryptomator.logging.DebugMode - Debug mode disabled

**Comment by macos-fuse-t** [comment]
It seems that move operation requires support for extended attributes which cryptomator doesn't implement.  I  suggest you open a bug on their side
