### ISSUE TITLE
Overwriting macFUSE library with fuse-t

### ISSUE THREAD

**Issue by fleetwoodmac** [macos-fuse-t/fuse-t#43]
Hello,

You mentioned on the developer wiki that it is possible to overwrite macFUSE libraries with fuse-T so that you don't have to recompile programs to directly work with fuse-T. I was wondering if you could give a guide on how to do so (even if it is not suggested). I am trying to test VeraCrypt and Kopia with Fuse-T, and there does not seem to be any documentation on how to use Fuse-T as a literal drop in replacement for macFUSE for end users (i.e. people that do not want to modify source code, at their own risk).

To clarify my situation, I do not have macFUSE installed at all, just FUSE-T. Would this involve renaming the libfuse-t.dylib files in /usr/local/lib or creating copies with specific names?

**Comment by macos-fuse-t** [comment]
You should contact the software authors. Drop in is meant for software developers not regular users.
