### ISSUE TITLE
ext4fuse fuse: reading error: Bad file descriptor

### ISSUE THREAD

**Issue by brandonros** [macos-fuse-t/fuse-t#46]
```
$ ./ext4fuse -d -f ~/Desktop/file.raw ~/Desktop/mnt
FUSE library version: 2.9.9
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.18
flags=0xfe00007b
max_readahead=0x00000000
   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00000000
   max_write=0x02000000
   max_background=0
   congestion_threshold=0
   unique: 2, success, outsize: 40
fuse: mount failed with errro: -1
fuse: reading error: Bad file descriptor
```

**Comment by brandonros** [comment]
I was trying to mount to a directory that did not yet exist.

**Comment by brandonros** [comment]
Doesn't really work, says `Server connection interrupted`

![image](https://github.com/macos-fuse-t/fuse-t/assets/8949910/07feae9c-d5f8-425d-94c3-34813b7bc3d1)

Can't really open the folder

**Comment by macos-fuse-t** [comment]
Perhaps something wrong with your image file? Are there errors from ext4fuse ?

**Comment by macos-fuse-t** [comment]
Ignore my previous comment:
I fixed the issue in the forked ext4fuse repo:
https://github.com/macos-fuse-t/ext4fuse

**Comment by brandonros** [comment]
@macos-fuse-t to clarify + double check: `fuse: reading error: Bad file descriptor` was a mistake on my end trying to `./ext4fuse` with a mount point that didn't exist

Are you saying you were able to fix the 2nd problem I had where `readdir` hangs?

**Comment by macos-fuse-t** [comment]
correct.

**Comment by brandonros** [comment]
@macos-fuse-t confirmed this fixes it. not sure what our options are upstreaming this to ext4fuse to fix this for others. really appreciate your help. let me bang on it a little more and see if i can break anything else

**Comment by brandonros** [comment]
I didn't realize ext4fuse was read only, fuse-ext2 is read + write but it hasn't been updated in a long time: https://github.com/alperakcan/fuse-ext2

**Comment by brandonros** [comment]
```diff
$ git diff configure.ac 
diff --git a/configure.ac b/configure.ac
index 452cb3a..c86abb8 100644
--- a/configure.ac
+++ b/configure.ac
@@ -141,7 +141,7 @@ AC_CHECK_FUNCS([    \
 
 # Checks for libraries
 AC_SEARCH_LIBS([sem_post], [pthread], [], [AC_MSG_ERROR([Can't find pthreads, please install it])])
-AC_SEARCH_LIBS([fuse_main], [osxfuse fuse], [], [AC_MSG_ERROR([Can't find libfuse, please install it])])
+AC_SEARCH_LIBS([fuse_main], [fuse-t], [], [AC_MSG_ERROR([Can't find libfuse, please install it])])
 AC_SEARCH_LIBS([com_err], [com_err], [], [AC_MSG_ERROR([Can't find comerr, please install it])])
 AC_SEARCH_LIBS([ext2fs_open], [ext2fs], [], [AC_MSG_ERROR([Can't find e2fslibs, please install it])])
```

```shell
./autogen.sh && CFLAGS="-I/usr/local/include/fuse -I/opt/homebrew/Cellar/e2fsprogs/1.47.0/include" LDFLAGS="-L/usr/local/lib -L/opt/homebrew/Cellar/e2fsprogs/1.47.0/lib" ./configure && make
```

I got it compiled and it works (read + write)

```shell
fuse-ext2 ext4_partition.img ~/Desktop/ext4 -o rw+,allow_other
```

Thanks!
