### ISSUE TITLE
Original Date/Time is changed when duplicating a file using the Finder CMD+D command

### ISSUE THREAD

**Issue by cipher-neo** [macos-fuse-t/fuse-t#49]
Latest version 1.0.35 which uses the experimental SMB backend server still changes the file date/time when duplicating a file using the Finder CMD+D command. Duplicating a file should not modify the file/date of a duplicate file.

**Comment by macos-fuse-t** [comment]
How are you testing?
I've just tested with the server itself and mtime didn't change.

**Comment by cipher-neo** [comment]
Opened a Cryptomator vault with its virtual drive set to use the fuse-t experimental with the -obackend=SMB option set. I selected one of my vault PDF files in the Finder and used the CMD+D duplicate function. The result was the last modified time was set to the current date and time and not the original files data and time.

**Comment by macos-fuse-t** [comment]
Please re-open this under Cryptomator. It's up to them to handle it properly.

**Comment by cipher-neo** [comment]
Well I beg to differ since the same operation using macFuse kext or WebDav for the virtual drive works correctly.

**Comment by macos-fuse-t** [comment]
As I said, use small letters for smb. Otherwise it still would nfs

**Comment by cipher-neo** [comment]
I’ll check but I’m pretty sure it was lowercase smb. I believe the autocorrect on my iPhone capitalized it when I typed the comment. I also checked to see if the nfs issue with the Finder file preview was present and it was not. That is another indicator I was using the smb backend and not nfs when I did my testing.

**Comment by macos-fuse-t** [comment]
I double checked it and it's still a bug in Cryptomator implementation. I advise you to open a bug on their git project.
