### ISSUE TITLE
Modification date/time is not preserved

### ISSUE THREAD

**Issue by dmahurin** [macos-fuse-t/fuse-t#5]
Modification date and times do not seem to be preserved in this filesystem.

Try
cp -a file mounted_dir/
rsync -a file mounted-dir/
touch -r file mounted-dir/dummy

**Comment by macos-fuse-t** [comment]
Yes, this seems to be a bug. I will fix it in the next release

**Comment by macos-fuse-t** [comment]
fixed in 1.0.2
