### ISSUE TITLE
Could not mount disc

### ISSUE THREAD

**Issue by gingerbeardman** [macos-fuse-t/fuse-t#50]
- https://github.com/thejoelpatrol/fusehfs
- Macintosh HFS CD-ROMs of Japanese origin
- eg. https://archive.org/details/@gingerbeardman?and[]=mediatype%3A%22software%22

<img width="372" alt="Screen shot 2024-01-26 at 13 46 15" src="https://github.com/macos-fuse-t/fuse-t/assets/49612/b30a837b-3c17-4fa2-bc47-64ae7408a45a">

**Comment by macos-fuse-t** [comment]
provide the instructions on how to reproduce this issue
