### ISSUE TITLE
Memory leak problem

### ISSUE THREAD

**Issue by LanYunDev** [macos-fuse-t/fuse-t#52]
Example code: https://github.com/macos-fuse-t/libfuse/blob/master/example/fusexmp_fh.c
Through the leaks tool in xcode.I found that there seems to be a memory leak, the following is the output of leaks --list

OS Version:      macOS 14.3 (23D56) arm64
Kernel: 23.3.0
Report Version:  7
Analysis Tool:   /usr/bin/leaks

Physical footprint:         6402K
Physical footprint (peak):  6402K
Idle exit:                  untracked

leaks Report Version: 3.0
Process 35655: 875 nodes malloced for 328159 KB
Process 35655: 16 leaks for 4240 total leaked bytes.

Leak: 0x124e040c0  size=256  zone: MallocHelperZone_0x104e90000
Leak: 0x124e041c0  size=256  zone: MallocHelperZone_0x104e90000
Leak: 0x124e042c0  size=256  zone: MallocHelperZone_0x104e90000
Leak: 0x124e043c0  size=256  zone: MallocHelperZone_0x104e90000
Leak: 0x124e044c0  size=256  zone: MallocHelperZone_0x104e90000
Leak: 0x124e045c0  size=256  zone: MallocHelperZone_0x104e90000
Leak: 0x124e046c0  size=256  zone: MallocHelperZone_0x104e90000
Leak: 0x124e047c0  size=512  zone: MallocHelperZone_0x104e90000
Leak: 0x124e04bc0  size=256  zone: MallocHelperZone_0x104e90000
Leak: 0x124e04cc0  size=256  zone: MallocHelperZone_0x104e90000
Leak: 0x124e04dc0  size=256  zone: MallocHelperZone_0x104e90000
Leak: 0x124e04ec0  size=256  zone: MallocHelperZone_0x104e90000
Leak: 0x124e04fc0  size=256  zone: MallocHelperZone_0x104e90000
Leak: 0x124e050c0  size=512  zone: MallocHelperZone_0x104e90000
Leak: 0x60000023c0c0  size=64  zone: DefaultMallocZone_0x104ecc000   OS_xpc_pipe  ObjC  libxpc.dylib
Leak: 0x600003434000  size=80  zone: DefaultMallocZone_0x104ecc000

**Comment by macos-fuse-t** [comment]
These are leaks from unclean exit in libfuse. It shouldn't cause problems.

**Comment by LanYunDev** [comment]
Thanks for the answer!
