### ISSUE TITLE
Install without root

### ISSUE THREAD

**Issue by netheril96** [macos-fuse-t/fuse-t#54]
Unlike macFuse that installs a kernel extension, fuse-t doesn't seem to require root privileges, since any user can start a NFS/SMB server on their own. So will it be possible to install this without root in the future?

**Comment by macos-fuse-t** [comment]
The installer writes files to /Library/Application Support this is why root is needed. It is pretty much a standard procedure.

**Comment by netheril96** [comment]
It is standard but it is not mandatory. I want to install it on $HOME/.local and test it without root privileges.

**Comment by macos-fuse-t** [comment]
I'll add an option to the installer to write files under a user folder.

**Comment by footlooseboss** [comment]
> I'll add an option to the installer to write files under a user folder.

convention:

| mode | option | installation path |
|----------|----------| ---------|
| single user    | _install for me only_    | ~/Library/Application Support |
| multi-user    | _install for everyone_    | /Library/Application Support |

> I want to install it on $HOME/.local

`ln -s ~/Library/Application\ Support/fuse-t ~/.local/fuse-t` post-install is probably the most compatible way to do this

**Comment by macos-fuse-t** [comment]
Local install:
installer -pkg fuse-t-macos-installer-1.0.37.pkg -target CurrentUserHomeDirectory
