### ISSUE TITLE
Unusable fuse-t mounts with restic 0.17.0 and macOS Sonoma

### ISSUE THREAD

**Issue by MichaelEischer** [macos-fuse-t/fuse-t#61]
We've recently added fuse-t support in restic and are now encountering a very weird issue where it is impossible to copy data from a mounted repository when using macOS Sonoma. Judging from the logs, the macOS NFS client seems to just lock up in an endless loop of opening and immediately closing the file in question. Older macOS versions however seem to work.

See https://github.com/restic/restic/issues/4971 for more details. There's also a fuse-t debug log at https://github.com/restic/restic/issues/4971#issuecomment-2267292121 . Compared to some other fuse-t debug log I could find (from https://github.com/macos-fuse-t/fuse-t/issues/45#issuecomment-1870659743), I noticed a few small differences, however, I don't see why those should be a problem. `blksize` is currently 0 for directories in restic, we use the full 64bits of `inode` and the other log I found includes "GetAttr from cache" log entries, which are not present with restic.

Do you have an idea what might be the problem?

**Comment by macos-fuse-t** [comment]
I don't see any errors in the log file. Is there an easy way for me to reproduce the issue? 
Could you also try a different backend by passing `-o backend=smb ` mount option or changing it in `/Library/Application\ Support/fuse-t/cfg/fuse-t.ini` file

**Comment by damoclark** [comment]
Hi Alex,

I've been working with Michael on this issue, trying to generate debugging information to assist with identifying the issue.  

I've changed my fuse-t configuration as you suggested by updating the `fuse-t.ini` file.  

fuse-t.ini file:
```ini
[Default]
debug=true
;nfc=false
;readonly=false
;namedattr=true
;attrcache=true
;nobrowse=false
;rwsize=0
;noatime=false
;nomtime=false
;location=fuse-t
backend=smb
```

This yielded a completely different problem.  The mount fails entirely, although no error is generated - restic is unaware of the failure. Navigating to the mount point reveals an empty directory and checking the output of the `mount` command does not show the mount.

Michael, here is how I mounted:

```bash
restic mount --key-hint=keyname --password-file=/path/to/file --repository-file=/path/to/repository/file /Users/<username>/restic
repository <hash> opened (version 2, compression level auto)
[0:35] 100.00%  253 / 253 index files loaded
Now serving the repository at /Users/<username>/restic
Use another terminal or tool to browse the contents of this folder.
When finished, quit with Ctrl-c here or umount the mountpoint.
  signal interrupt received, cleaning up
unable to umount (maybe already umounted or still in use?): unmount /Users/<username>/restic: invalid argument
```

The repository backend is the rest server, version 0.13.0.

Here is the complete log using the smb backend.

```
time="2024-08-05T09:22:07+10:00" level=info msg="comm socket: 3"
time="2024-08-05T09:22:07+10:00" level=info msg="montor socket: 4"
time="2024-08-05T09:22:07+10:00" level=debug msg="Sent 56"
time="2024-08-05T09:22:07+10:00" level=debug msg="Received {40 0 2}"
time="2024-08-05T09:22:07+10:00" level=debug msg="init reply {Major:7 Minor:17 MaxReadahead:131072 Flags:32 MaxBackground:0 CongestionThreshold:0 MaxWrite:16777216}"
time="2024-08-05T09:22:07+10:00" level=info msg="Server version 1.0.38 (6784d4c9cbd7b78b00ddf89f4cad29f53e7ee7fb) running at [::1]:52200"
time="2024-08-05T09:22:07+10:00" level=info msg="Mounting: /Users/<username>/restic"
time="2024-08-05T09:22:07+10:00" level=info msg="mount [-o noauto,ro,nomdatacache -t smbfs //Guest@fuse-t-0._smb._tcp.local/restic /Users/<username>/restic]"
time="2024-08-05T09:22:08+10:00" level=debug msg=Negotiate
time="2024-08-05T09:22:08+10:00" level=debug msg=Negotiate
time="2024-08-05T09:22:08+10:00" level=debug msg=SessionSetup
time="2024-08-05T09:22:08+10:00" level=debug msg=sessionServerSetup
time="2024-08-05T09:22:08+10:00" level=debug msg=SessionSetup
time="2024-08-05T09:22:08+10:00" level=debug msg=sessionServerSetupChallenge
time="2024-08-05T09:22:08+10:00" level=debug msg="auth user: GUEST"
time="2024-08-05T09:22:08+10:00" level=debug msg=TreeConnect
time="2024-08-05T09:22:08+10:00" level=debug msg="TreeConnect: \\\\fuse-t-0._smb._tcp.local\\RESTIC"
time="2024-08-05T09:22:08+10:00" level=debug msg="new file tree 2555498934"
time="2024-08-05T09:22:08+10:00" level=debug msg=fileTreeCreate
time="2024-08-05T09:22:08+10:00" level=debug msg="create name: , options 1, disp 1"
time="2024-08-05T09:22:08+10:00" level=debug msg="Lookup handle 0, name /"
time="2024-08-05T09:22:08+10:00" level=debug msg="Lookup 1//"
time="2024-08-05T09:22:08+10:00" level=debug msg="Sent 42"
time="2024-08-05T09:22:40+10:00" level=debug msg="Received {16 -2 3}"
time="2024-08-05T09:22:40+10:00" level=debug msg="Open: doesn't exists: "
time="2024-08-05T09:22:40+10:00" level=debug msg=Echo
time="2024-08-05T09:22:40+10:00" level=debug msg=Echo
time="2024-08-05T09:22:40+10:00" level=debug msg=Echo
time="2024-08-05T09:22:40+10:00" level=debug msg=TreeDisconnect
time="2024-08-05T09:22:40+10:00" level=debug msg=Logoff
time="2024-08-05T09:22:40+10:00" level=error msg="error: connection error: EOF"
time="2024-08-05T09:22:40+10:00" level=debug msg="receiver finished"
time="2024-08-05T09:22:40+10:00" level=error msg="exit status 64"
time="2024-08-05T09:22:40+10:00" level=warning msg="receiveRequest error: read unix ->: use of closed network connection"
time="2024-08-05T09:23:41+10:00" level=info msg="Parent process has died"
```

At time `2024-08-05T09:22:40+10:00`, I sent restic a SIGINT (Ctrl-C).

Next, I used the fuse-t sshfs tool (installed from sshfs-macos-installer-1.0.2.pkg) to mount a filesystem.  It was successful with the same `fuse-t.ini` config described above, using smb. 

The mount is shown as follows:

```bash
mount|grep restic
//Guest:@fuse-t-0._smb._tcp.local/restic on /Users/<username>/restic (smbfs, nodev, nosuid, noowners, mounted by <username>)
cd ~/restic
ls -l
<directory listing>
```

The log file is substantially longer given it worked.  It's of a `/tmp/` directory for a remote host so completely unrelated of course to the restic source.  Hoping this offers some insights into the issue.

[fuse-t.log](https://github.com/user-attachments/files/16489268/fuse-t.log)

**Comment by macos-fuse-t** [comment]
Hi Damien,
I traced the problem to the recent changes to anacrolix/fuse package you guys use. After cloning their package and trying to run a loopback sample I'm unable to read/write files so my guess it's related to what you're seeing. I'm looking into it and will send a PR with a fix to the module's owner. I'll update you when it's done.

**Comment by macos-fuse-t** [comment]
Damien  and Michael, please test the attached pre-release. It should resolve the issue.
https://github.com/macos-fuse-t/fuse-t/releases/tag/1.0.39d

**Comment by damoclark** [comment]
Thanks Alex for your quick response on this.

Michael, when you have a chance to create a test build with the updated dependency, let us know in the original restic ticket.  I'll test it at my end and update everyone on the outcome.

Cheers,
D.

**Comment by MichaelEischer** [comment]
@macos-fuse-t Any updates on the anacrolix/fuse fix? Can you provide a few more details on the cause of the issue?

**Comment by alexfs** [comment]
anacrolix implementation keeps incrementing inode numbers for the same files for every lookup request. fuse-t maps inode number to nfs file handle which is used as a unique identifier for a file. Changing it for the same file is not a problem per se but macos for some reason executes lookup request twice for the same file and returning different file handles confuses it, that's why it enters infinite loop of lookup requests.
My workaround is to cache lookup responses in fuse-t for a few seconds but a better fix is to do the same on anacrolix side or even better not change inode numbers at all just like libfuse does.

**Comment by MichaelEischer** [comment]
> anacrolix implementation keeps incrementing inode numbers for the same files for every lookup request

Thanks for the information. I've dug a bit into the anacrolix/fuse code and it looks like restic implements Lookup() differently than expected by the library. Before I'll go into more detail on that, let's start with a recap of the problem for future reference.

The fuse protocol ([manpage](https://man7.org/linux/man-pages/man4/fuse.4.html)) uses inodes in two places. The reply for a `FUSE_LOOKUP` contains two fields referring to inodes:
```
uint64_t nodeid;            /* Inode ID */
uint64_t generation;        /* Inode generation */
```

In addition, the `fuse_attr` struct also contains a field `uint64_t ino;`. The `ino` field is what is returned when using the `stat` syscall on the fuse file. In contrast the `nodeid` and `generation` are used in the kernel to reference to a specific file, these can differ from the `ino` field.

In the bazil/anacrolix fuse library, the `ino` field is retrieved by a call to `Node.Attr(ctx context.Context, attr *fuse.Attr) error`. If it is zero, then an inode value is generated on demand (see [saveLookup()](https://github.com/anacrolix/fuse/blob/e4651fbc304dedafa99ae7779d77e52db229565e/fs/serve.go#L1682-L1692) ). The nodeid and generation fields, however, are automatically assigned in [saveNode()](https://github.com/anacrolix/fuse/blob/e4651fbc304dedafa99ae7779d77e52db229565e/fs/serve.go#L562-L585).

If a Node object was returned in the past, then it's `nodeid` and `generation` are reused. The corresponding id lookup compares by object identity. That is, if a [Lookup()](https://github.com/anacrolix/fuse/blob/e4651fbc304dedafa99ae7779d77e52db229565e/fs/serve.go#L166-L174) implementation returns different objects for the same path, then those will be assigned different `nodeid`s. And that is the core of the initially mentioned problem, where macOS apparently calls lookup twice and hence ends up with two different Node instances of the same file.

The intended solution is to implement `Lookup` and other methods such that they return the same `Node` object for the same file. From https://github.com/anacrolix/fuse/blob/e4651fbc304dedafa99ae7779d77e52db229565e/fs/serve.go#L90-L94:

> // Methods returning Node should take care to return the same Node
> // when the result is logically the same instance. Without this, each
> // Node will get a new NodeID, causing spurious cache invalidations,
> // extra lookups and aliasing anomalies. This may not matter for a
> // simple, read-only filesystem.

However, due to the way macOS and fuse-t interact with the filesystem, the latter exception for read-only filesystems no longer applies.

This means, that an implementation has to cache or pre-create the Node objects. For large filesystems this could result in running out of memory if all those objects have to be kept permanently. To avoid that problem, a [`NodeForgetter` interface](https://github.com/anacrolix/fuse/blob/e4651fbc304dedafa99ae7779d77e52db229565e/fs/serve.go#L206-L213) exists to receive notifications once a Node object is no longer in use.

**Comment by MichaelEischer** [comment]
I just did a few tests on macOS Sonoma myself and tried copying a few files from the mounted folder.

- fuse-t 1.0.38 + restic master: command hangs
- fuse-t 1.0.38 + https://github.com/restic/restic/pull/5048 (implements my suggestion above) : works as expected
- fuse-t 1.0.41 + restic master: command hangs
- fuse-t 1.0.41 + PR : works as expected
- fuse-t 1.0.42: `cp` reports a `could not copy extended attributes to [...]: Result too large` error. Otherwise, same behavior as previous version.

**Comment by MichaelEischer** [comment]
And one more: 1.0.39d work with and without the PR.

**Comment by MichaelEischer** [comment]
Fixed by https://github.com/anacrolix/fuse/pull/11 . Although ideally, implementations using anacrolix/fuse should follow the implementation outlined in https://github.com/macos-fuse-t/fuse-t/issues/61#issuecomment-2336794151 .
