### ISSUE TITLE
Installation on Apple Silicon: ssh-askpass not found in brew's default location

### ISSUE THREAD

**Issue by krzysztofjeziorny** [macos-fuse-t/fuse-t#65]
(Excuse me if it's a duplicate of some issue.)

Installing fuse-t with `brew` on a Mac Silicon system (Sonoma 14.6.1) results in an error saying `ssh-askpass` couldn't be found under `/usr/local/bin`. The thing is, the clean [Homebrew installations](https://docs.brew.sh/Installation) use `/opt/homebrew/bin` path instead. 

> The script installs Homebrew to its default, supported, best prefix (/opt/homebrew for Apple Silicon, /usr/local for macOS Intel

Here's the log message:

```
Error: Failure while executing; `/usr/bin/sudo -u root -A -E LOGNAME=kj USER=kj USERNAME=kj -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/fuse-t/1.0.38/fuse-t-macos-installer-1.0.38.pkg -target /` exited with 1. Here's the output:
sudo: unable to run /usr/local/bin/ssh-askpass: No such file or directory
sudo: no password was provided
sudo: a password is required
```

```
which ssh-askpass
/opt/homebrew/bin/ssh-askpass
```

I installed fuse-t on an Intel iMac without a problem. Thanks for help or hints how to work around the issue.

**Comment by macos-fuse-t** [comment]
I'm not sure I'm following your question, who's or what's invoking ssh-askpass?

**Comment by krzysztofjeziorny** [comment]
> what's invoking ssh-askpass?

The fuse-t installation process.

**Comment by macos-fuse-t** [comment]
fuse-t installation script doesn't invoke ssh-askpass.

**Comment by krzysztofjeziorny** [comment]
I didn't make this up :)

Maybe brew on my systems is borked or there is some explanation. Thanks anyway.

**Comment by krzysztofjeziorny** [comment]
Mystery solved, a `LaunchAgent` from an older synced installation of `ssh-askpass` was still being loaded, interrupting the process.

Sorry for confusing :)
