### ISSUE TITLE
call ::link always return success

### ISSUE THREAD

**Issue by xuyouqiao2005** [macos-fuse-t/fuse-t#66]
No matter what results I return, it always return success when i call ::link

eg:
unique: 56, opcode: LINK (13), nodeid: 1, insize: 56, pid: 0
   unique: 56, error: -2 (No such file or directory), outsize: 16

as you can see, it returned ENOENT, but function ::link(src, dst) return zero

**Comment by macos-fuse-t** [comment]
I need to check if a hard link is possible. why don't you use a symlink?

**Comment by xuyouqiao2005** [comment]
I just want to use the ::link function. TvT
