### ISSUE TITLE
Does fuse-t exist with cached inode information?

### ISSUE THREAD

**Issue by xuyouqiao2005** [macos-fuse-t/fuse-t#67]
I use sshfs to mount, such as:

`sshfs xxx@127.0.0.1:/User/xxx/test mtest`

after mounted, I make a new file in mtest/ v.txt and delete file v.txt. but i still can find v.txt exists.

eg: (no press tab in any cmd)
```
$ touch mtest/v.txt
$ rm mtest/v.txt
$ ls mtest/v.txt
mtest/v.txt
(A few seconds later run ls again)
$ ls mtest/v.txt
ls: mtest/v.txt:No such file or directory
```
<img width="348" alt="1726196162173" src="https://github.com/user-attachments/assets/3fc469e7-e87a-4f33-83a6-8e8cde38237f">

**Comment by macos-fuse-t** [comment]
fixed in 1.0.41
