### ISSUE TITLE
ext4fuse fails: Library not loaded error

### ISSUE THREAD

**Issue by mattmartini** [macos-fuse-t/fuse-t#73]
I would like to use `fuse-t` and `ext4fuse` to mount `ext4` filesystems.

I used `homebrew` to install the `macfuse cask` and then compiled `ext4fuse` from source.  When I tried to mount an `ext4` volume I was confronted  by `"System Extension Blocked"`  Not really wanting to enable this because other users reported issues.  In comments I discovered `fuse-t`.

I installed `fuse-t` :
`brew remove --cask macfuse`
`brew install macos-fuse-t/homebrew-cask/fuse-t`

and then tried to mount the filesystem:
`sudo ext4fuse /dev/disk10s2  ~/ext4_mnt -o allow_other`

This failed with:
```
dyld[95128]: Library not loaded: /usr/local/lib/libfuse.2.dylib
  Referenced from: <163C00AB-5332-3C6E-98A4-45B813167AA8> /usr/local/bin/ext4fuse
  Reason: tried: '/usr/local/lib/libfuse.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libfuse.2.dylib' (no such file), '/usr/local/lib/libfuse.2.dylib' (no such file)
Abort trap: 6
```

I then realized that this might be due to compiling `ext4fuse` with `macfuse` and then trying to run it under `fuse-t`.

So then I tried to re-compile `ext4fuse`:

`make clean`
`make`

However, this failed too:
```
Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found
cc  -DFUSE_USE_VERSION=26 -std=gnu99 -g3 -Wall -Wextra -DEXT4FUSE_VERSION=\"v0.1.3-20-g6b23d8d\" -mmacosx-version-min=10.5 -D_FILE_OFFSET_BITS=64   -c -o fuse-main.o fuse-main.c
fuse-main.c:14:10: fatal error: 'fuse.h' file not found
#include <fuse.h>
         ^~~~~~~~
1 error generated.
make: *** [fuse-main.o] Error 1
```

I'm at a loss of where to go from here.  It seems like I need `fuse.h`, where do I find that?

About my Mac:  `Mac Studio (2023) M2 Ultra, Sonoma 14.6.1`

**Comment by macos-fuse-t** [comment]
clone this repo
https://github.com/macos-fuse-t/ext4fuse

**Comment by mattmartini** [comment]
That worked great.  Thank you!
